# Generated by Django 3.2.8 on 2021-10-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('tipodocumento', models.IntegerField(max_length=1)),
                ('documento', models.IntegerField(max_length=15)),
                ('residencia', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(max_length=15)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
